---
# -----------------------------
# This playbook transfer thekubeconfig file from the remote node to the local node.
# It creates a merged kubeconfig file in order to export the context of both local and remote clusters.
# Finally, it perform the in-band peering from the central cluster to the local node.
# -----------------------------

- name: Transfer kubeconfig from remote to local and prepare it
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  roles:
    - role: liqo-get-kubeconfig-remote

- name: Transfer modified kubeconfig to remote node
  hosts: localhost

  roles:
    - role: liqo-push-kubeconfig-local
    - role: liqo-incoming