- name: Create or Update KubeVirt Manager Ingress
  kubernetes.core.k8s:
    state: present
    namespace: kubevirt-manager
    definition: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: kubevirt-manager-ingress
        namespace: kubevirt-manager
        annotations:
          kubernetes.io/ingress.class: nginx
      spec:
        rules:
          - http:
              paths:
                - path: /kubevirt
                  pathType: Prefix
                  backend:
                    service:
                      name: kubevirt-manager
                      port:
                        number: 8080
  tags:
    - kubevirt
