- name: "Create an Ingress for KubeVirt Manager (host-based)"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: kubevirt-manager-ingress
        namespace: kubevirt-manager
        annotations:
          kubernetes.io/ingress.class: "nginx"
      spec:
        ingressClassName: "nginx"
        rules:
          - host: kubevirt.local
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubevirt-manager
                      port:
                        number: 8080
  tags:
    - kubevirt
